# Generated by Django 4.0.4 on 2022-05-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=300)),
                ('detail', models.CharField(max_length=1000)),
            ],
        ),
    ]
